modLoader="javafml"
loaderVersion="[43,)"
license="Unlicense"
[[mods]]
modId="blahaj"
version="${file.jarVersion}"
displayName="Blåhaj - Rebooped"
displayURL="https://wavee.dog"
logoFile="icon.png"
credits="Made by Hibi"
authors="Made by Hibi, ported to Forge by agnor99, fixed by wavee"

description='''
Soft toy, shark mod, 16px.
'''
[[dependencies.blahaj]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blahaj]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20.2)"
    ordering="NONE"
    side="BOTH"
